services:
  quic-lab:
    container_name: quic-lab
    image: ghcr.io/quic-lab/quic-lab
    ports:
      - "80:80"
    dns:
      - "1.1.1.1"
      - "2606:4700:4700::1111"
      - "8.8.8.8"
      - "2001:4860:4860::8888"
    volumes:
      - ./in:/app/in
      - ./out:/app/out
