[package]
name = "runner"
version = "1.0.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
probes = { path = "../probes" }
anyhow = "1"
rayon = "1.10"
indicatif = "0"
atty = "0.2.14"
log = "0"