[package]
name = "core"
version = "1.0.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1"
env_logger = "0"
rand = "0"
toml = "0"
governor = "0"
tquic = { version = "1", features = ["h3"] }
serde_json = "1"